"""
Django settings for retegi project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import Csv, config
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('DJANGO_SECRET_KEY')

DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv(),
)

_CSRF_ORIGINS_RAW = config('DJANGO_CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in _CSRF_ORIGINS_RAW.split(',')
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS y cookies: en producción activar vía .env. Para probar el contenedor en
# http://127.0.0.1:8090 sin TLS, poner DJANGO_SECURE_SSL_REDIRECT=False y
# DJANGO_SESSION_COOKIE_SECURE=False DJANGO_CSRF_COOKIE_SECURE=False.
if not DEBUG:
    SECURE_SSL_REDIRECT = config(
        'DJANGO_SECURE_SSL_REDIRECT',
        default=True,
        cast=bool,
    )
    SESSION_COOKIE_SECURE = config(
        'DJANGO_SESSION_COOKIE_SECURE',
        default=True,
        cast=bool,
    )
    CSRF_COOKIE_SECURE = config(
        'DJANGO_CSRF_COOKIE_SECURE',
        default=True,
        cast=bool,
    )
    SECURE_HSTS_SECONDS = config(
        'DJANGO_SECURE_HSTS_SECONDS',
        default=31536000,
        cast=int,
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
        'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
        default=True,
        cast=bool,
    )
    SECURE_HSTS_PRELOAD = config(
        'DJANGO_SECURE_HSTS_PRELOAD',
        default=False,
        cast=bool,
    )
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

LANGUAGE_CODE = config('DJANGO_LANGUAGE_CODE', default='es')

TIME_ZONE = config('DJANGO_TIME_ZONE', default='Europe/Madrid')

DEFAULT_SQLITE_URL = (
    'sqlite:////'
    + str((BASE_DIR / 'data' / 'db.sqlite3').resolve()).replace('\\', '/')
)

_DATABASE_URL = (config('DATABASE_URL', default='') or '').strip()
DATABASE_URL = _DATABASE_URL or DEFAULT_SQLITE_URL

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=0),
}

INSTALLED_APPS = [
    'parler',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'applications.home',
    'rosetta',
    'tinymce',
    'allauth_ui',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'widget_tweaks',
    'django_celery_beat',
    'channels',
    'applications.assistant',
    'slippers',
]

ALLAUTH_UI_THEME = "light"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

ROOT_URLCONF = 'retegi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'retegi.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'

STATIC_DIR = BASE_DIR / 'static'
STATICFILES_DIRS = [str(STATIC_DIR)] if STATIC_DIR.is_dir() else []

STATIC_ROOT = BASE_DIR / 'staticfiles'

TINYMCE_API_KEY = config('TINYMCE_API_KEY', default='')
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 600,
    'plugins': 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help | fontsizeselect',
    'fontsize_formats': '8pt 10pt 12pt 14pt 15pt 16pt 17pt 18pt 24pt 36pt',
    'api_key': TINYMCE_API_KEY,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

BASE_URL = config('DJANGO_BASE_URL', default='localhost')

LOGOUT_REDIRECT_URL = 'home_app:home'
LOGIN_REDIRECT_URL = 'home_app:home'

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)

EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')

CONTACT_EMAIL = config('CONTACT_EMAIL', default='contact@example.com')

BREVO_API_KEY = config('BREVO_API_KEY', default='')
BREVO_SENDER_EMAIL = config('BREVO_SENDER_EMAIL', default='')
BREVO_SENDER_NAME = config('BREVO_SENDER_NAME', default='retegi.eus')
BREVO_TO_EMAIL = config('BREVO_TO_EMAIL', default='')

SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')

REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

CELERY_BROKER_URL = config(
    'CELERY_BROKER_URL',
    default=f'redis://{REDIS_HOST}:{REDIS_PORT}/0',
)

CELERY_RESULT_BACKEND = config(
    'CELERY_RESULT_BACKEND',
    default=CELERY_BROKER_URL,
)

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

ASGI_APPLICATION = 'retegi.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

LANGUAGES = [
    ('eu', _('Euskara')),
    ('es', _('Castellano')),
    ('en', _('English')),
]

PARLER_DEFAULT_LANGUAGE_CODE = 'en'

PARLER_LANGUAGES = {
    None: (
        {'code': 'eu'},
        {'code': 'es'},
        {'code': 'en'},
    ),
    'default': {
        'fallbacks': ['es'],
        'hide_untranslated': False,
    }
}
