# Generated by Django 5.1.2 on 2025-02-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='content',
            new_name='_content',
        ),
        migrations.RenameField(
            model_name='posttranslation',
            old_name='summary',
            new_name='_summary',
        ),
        migrations.RenameField(
            model_name='posttranslation',
            old_name='title',
            new_name='_title',
        ),
    ]
