# Generated by Django 5.1.2 on 2026-05-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_content_posttranslation__content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttranslation',
            old_name='_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posttranslation',
            old_name='_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='posttranslation',
            old_name='_title',
            new_name='title',
        ),
    ]
